// BurgerBuilder actions
export const INIT_STATE_FROM_SERVER = 'INIT_STATE_FROM_SERVER';
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const SET_PRICES = 'SET_PRICES';
export const FETCH_DATA_FAILED = 'FETCH_DATA_FAILED';

// Order actions
export const POST_ORDER_START = 'POST_ORDER_START';
export const POST_ORDER_SUCCEDED = 'POST_ORDER_SUCCEDED';
export const POST_ORDER_FAILED = 'POST_ORDER_FAILED';
export const ORDER_INIT = 'ORDER_INIT';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';